format = """
[](#4A235A )\
[  ](bg:#4A235A  fg:#ffffff)\
$username\
$hostname\
[](bg:#154360 fg:#4A235A)\
$directory\
[](fg:#154360 bg:#1A5276)\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
[](fg:#1A5276 bg:#1F618D)\
$python\
$java\
$custom\
[](fg:#1F618D bg:#424949)\
$docker_context\
[](fg:#424949)\
$line_break\
$battery\
$time\
$character
"""
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#4A235A"
style_root = "bg:#CB4335"
format = '[$user]($style)'
disabled = false

[hostname]
disabled = false
ssh_only = false
format = '[@$ssh_symbol$hostname ]($style)'
style = "bg:#4A235A"

[directory]
style = "bg:#154360"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#1A5276"
format = '[ $symbol](fg:#F39C12  $style)[ $branch ]($style)'

[git_status]
style = "bg:#1A5276"
format = '[$all_status$ahead_behind ]($style)'

[git_commit]
style = "bg:#1A5276"
commit_hash_length = 8

[git_metrics]
added_style = "bg:#1A5276 fg:#58D68D"
deleted_style = "bg:#1A5276 fg:#fC7063"
format = '[⁺$added]($added_style)[·](bg:#1A5276 fg:#ffffff)[$deleted⁻]($deleted_style)'
disabled = false

[python]
style = "bg:#1F618D"
symbol = " "
format = '[ ${symbol}]($style fg:#F1C40F)[(${version} )(\($virtualenv\) )]($style)'

[java]
symbol = " "
style = "bg:#1F618D"
format = '[ $symbol]($style fg:#FFC90C)[($version) ]($style)'

[custom.clj]
command = "clojure -version 2>&1 | cut -d' ' -f4"  # shows output of command
ignore_timeout = true
files = ["deps.edn"]       # can specify filters
symbol = ""
style = "bg:#1F618D"
format = "[$symbol](fg:#58D68D $style)[ $output]($style)"

[docker_context]
symbol = "󰡨"
style = "bg:#424949"
format = '[ $symbol](bold fg:#3498DB $style)[ $context ]($style)'

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂇 "

[[battery.display]]
threshold = 60
discharging_symbol = '󰁿 '
style = 'bold green'

[[battery.display]]
threshold = 30
discharging_symbol = '󰁼 '
style = 'bold yellow'

[[battery.display]]
threshold = 15
discharging_symbol = '󰁺 '
style = 'bold red'

[[battery.display]]
threshold = 5
discharging_symbol = '󰂎 '
style = 'bold red'

[time]
disabled = false
time_format = "%r" # https://docs.rs/chrono/0.4.7/chrono/format/strftime/index.html
style = "fg:#AF7AC5 " # bg:#33658A style = "bg:"
format = '[ $time ]($style)'

[character]
success_symbol = "[⮕](bold fg:#58D68D) "
error_symbol = "[⮕](bold fg:#E74C3C) "
