
format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$docker_context\
$python\
$java\
$custom\
$env_var\
$line_break\
$jobs\
$battery\
$time\
$status\
$character\
"""

[battery]
full_symbol = "󰁹"
charging_symbol = "󰂇 "

[[battery.display]]
threshold = 60
discharging_symbol = '󰁿'
style = 'bold green'

[[battery.display]]
threshold = 30
discharging_symbol = '󰁼'
style = 'bold yellow'

[[battery.display]]
threshold = 15
discharging_symbol = '󰁺'
style = 'bold red'

[[battery.display]]
threshold = 5
discharging_symbol = '󰂎'
style = 'bold red'

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[docker_context]
format = "via [🐳 $context](blue bold)"

[git_commit]
commit_hash_length = 8

[git_metrics]
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false

[custom.clj]
command = "clojure-version"  # shows output of command
ignore_timeout = true
files = ["deps.edn"]       # can specify filters
symbol = " clojure"
style = "bold green"
format = "[$symbol $output]($style) "

[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = '%T'
utc_time_offset = '-5'
#time_range = '10:00:00-14:00:00'
